<script lang="ts">
  import { onMount } from 'svelte';
  import { fetchCatalog, type CatalogRequestState } from '$lib/catalog-fetch';
  export let data: { id: string };
  let detail: any; let loading = true; let state: CatalogRequestState = 'success';
  async function load() { loading = true; state = 'success'; const result = await fetchCatalog<any>(`/api/catalog/publications/${data.id}`); if (result.state === 'success') detail = result.data; else state = result.state; loading = false; }
  onMount(load);
</script>
{#if loading}<p aria-live="polite">読み込み中…</p>{:else if state === 'not-found'}<p role="alert">巻が見つかりません。</p><button onclick={() => void load()}>再試行</button>{:else if state === 'unavailable'}<p role="alert">巻は現在利用できません。</p><button onclick={() => void load()}>再試行</button>{:else if state === 'network'}<p role="alert">ネットワークに接続できませんでした。</p><button onclick={() => void load()}>再試行</button>{:else if state === 'error'}<p role="alert">巻の読み込みに失敗しました。</p><button onclick={() => void load()}>再試行</button>{:else}<nav><a href={`/series/${detail.seriesId}`}>← {detail.seriesName}</a></nav><h1>{detail.displayName}</h1>{#if detail.credits?.length}<h2>クレジット</h2><ul>{#each detail.credits as credit}<li><a href={`/${credit.kind === 'creator' ? 'creators' : credit.kind === 'group' ? 'groups' : 'publishers'}/${credit.id}`}>{credit.displayName}</a> · {credit.role}</li>{/each}</ul>{/if}<h2>利用可能なリリース</h2>{#if detail.releases?.length}<ul class="releases">{#each detail.releases as release}<li><span>リリース {release.id} · {release.pageCount} ページ</span><a class="read" href={`/reader/releases/${release.id}`}>読む</a></li>{/each}</ul>{:else}<p aria-live="polite">利用可能なリリースはありません。</p>{/if}{/if}
<style>.releases { padding:0; list-style:none; display:grid; gap:.5rem; }.releases li { display:flex; align-items:center; justify-content:space-between; gap:1rem; padding:.8rem; background:#1b1d22; border-radius:.5rem; }.read { padding:.45rem .7rem; border-radius:.4rem; background:#d9e8ff; color:#101114; font-weight:700; text-decoration:none; }</style>
